#!/usr/bin/env python3
"""Claude Code Stop hook for task-local handoff snapshots shared with Codex.

Every session resolves to a task. A valid current or explicit task wins; otherwise
the default task is ``main``. Root-level process/auto/recent/guard payloads are
legacy data and are never read or written.
"""

import datetime as _dt
import json
import os
import pathlib
import re
import subprocess
import sys
from typing import Any

from task_routing import (
    bind_task,
    normalize_task_id,
    resolve_task_id as resolve_bound_task_id,
    task_payload_rel,
    task_state_dir,
    workspace_root,
)


PROCESS_NAME = "process.md"
AUTO_NAME = "process.auto.md"
GUARD_NAME = "context_guard.json"
DEFAULT_AUTO_COMPACT_CLEAR_THRESHOLD = 3

# Task-id patterns supported in user prompts:
#   task=<id>, task-id=<id>, task_id=<id>, 任务=<id>
# ID must match: ^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$
TASK_ID_IN_PROMPT_RE = re.compile(
    r"(?:task(?:-id|_id)?|任务)\s*[=＝]\s*([a-zA-Z0-9][a-zA-Z0-9._-]{0,79})",
    re.IGNORECASE,
)


def now() -> str:
    return _dt.datetime.now().astimezone().isoformat(timespec="seconds")


def run(cmd: list[str], cwd: pathlib.Path) -> str:
    try:
        return subprocess.check_output(
            cmd, cwd=str(cwd), stderr=subprocess.STDOUT, text=True, timeout=5,
        ).strip()
    except Exception:
        return ""


def parse_task_id_from_text(text: str | None) -> str | None:
    """Extract task-id from text using supported patterns."""
    if not text:
        return None
    match = TASK_ID_IN_PROMPT_RE.search(text)
    if match:
        return normalize_task_id(match.group(1))
    return None


def read_guard(path: pathlib.Path) -> dict[str, Any]:
    default = {
        "auto_compact_count": 0,
        "clear_required": False,
        "threshold": DEFAULT_AUTO_COMPACT_CLEAR_THRESHOLD,
        "last_event": "",
        "last_trigger": "",
        "last_source": "",
        "last_turn_id": "",
        "last_transcript": "",
        "last_updated": "",
        "last_reset_source": "",
        "last_reset_at": "",
    }
    if not path.exists():
        return default
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default
    if isinstance(loaded, dict):
        default.update(loaded)
    return default


def write_guard(path: pathlib.Path, guard: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    guard["last_event"] = "Stop"
    guard["last_updated"] = now()
    path.write_text(json.dumps(guard, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_auto_snapshot(
    sdir: pathlib.Path,
    root: pathlib.Path,
    task_id: str,
    session_id: str,
    cwd: str,
) -> pathlib.Path:
    branch = run(["git", "branch", "--show-current"], root)
    head = run(["git", "rev-parse", "--short", "HEAD"], root)
    status = run(["git", "status", "--short"], root)
    diff_stat = run(["git", "diff", "--stat"], root)

    handoff_rel = task_payload_rel(task_id, PROCESS_NAME)

    auto_path = sdir / AUTO_NAME
    auto_path.parent.mkdir(parents=True, exist_ok=True)
    auto_path.write_text(
        f"""# Process Auto Snapshot

Updated: {now()}
Hook Event: Stop
Session Source: claude-code
Compaction Trigger: (none)
Workspace: {root}
Task ID: {task_id}
Branch: {branch or "(none)"}
HEAD: {head or "(none)"}
Session ID: {session_id or "(none)"}
CWD: {cwd or "(none)"}

## Process State Health

This auto snapshot was written by Claude Code's Stop hook.
Semantic task state belongs in `{handoff_rel}`.

## Shared Handoff (Claude Code ↔ Codex)

Task-local handoff file: `{handoff_rel}`

- Use `{handoff_rel}` for semantic task state.
- Both sides (Claude Code and Codex) read/write this same file.
- This auto snapshot is supporting evidence only — always prefer `{handoff_rel}`.

## Context Guard

Guard File: {sdir / GUARD_NAME}
Auto Compact Count: (managed by Codex)
Clear Required: (managed by Codex)

## Git Status

```text
{status or "clean or unavailable"}
```

## Diff Stat

```text
{diff_stat or "none or unavailable"}
```

## Resume Rule

1. Read `{handoff_rel}` first after `resume`, `compact`, or `clear`.
2. This auto snapshot is supporting evidence only.
3. Semantic task state belongs in `{handoff_rel}`.

---
Generated by Claude Code Stop hook (context_handoff.py)
Compatible with Codex .agents/state/ layout
Task-id handoff: enabled
""",
        encoding="utf-8",
    )
    return auto_path


def main() -> int:
    raw = sys.stdin.read()
    data: dict[str, Any] = {}
    if raw.strip():
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            pass
    if not isinstance(data, dict):
        data = {}

    session_id = str(data.get("session_id") or "")
    cwd_str = str(data.get("cwd") or os.getcwd())
    cwd = pathlib.Path(cwd_str).expanduser().resolve()

    root = workspace_root(cwd)

    task_id: str | None = None
    for key in ("task_id", "task-id", "prompt", "message", "additionalContext"):
        value = data.get(key, "")
        if not isinstance(value, str) or not value:
            continue
        task_id = normalize_task_id(value) or parse_task_id_from_text(value)
        if task_id:
            break
    task_id = resolve_bound_task_id(root, task_id, session_id)
    bind_task(root, task_id, session_id)

    sdir = task_state_dir(root, task_id)

    # Write auto snapshot
    auto_path = write_auto_snapshot(sdir, root, task_id, session_id, cwd_str)

    # Update context guard (non-destructive — preserve Codex fields)
    guard_path = sdir / GUARD_NAME
    guard = read_guard(guard_path)
    write_guard(guard_path, guard)

    rel = str(auto_path.relative_to(root)) if auto_path.is_relative_to(root) else str(auto_path)

    handoff_rel = task_payload_rel(task_id, PROCESS_NAME)

    output = {
        "systemMessage": (
            f"Stop hook: wrote auto snapshot to {rel}\n"
            f"Task ID: {task_id}\n"
            f"Handoff file (shared with Codex): {handoff_rel}\n"
            f"Next resume: read `{handoff_rel}` for task state"
        ),
    }
    sys.stdout.write(json.dumps(output, ensure_ascii=False))
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
